#!/usr/bin/env python3
"""Apply displayName and completionMessage updates to DailyArtwork.swift."""

import re
import sys

SWIFT_PATH = "../One Hue/Daily Artwork/DailyArtwork.swift"

# Combined updates from all 4 agents: id -> (displayName, completionMessage)
updates = {
    # ── January through March ──
    "snowyOwlPerch": ("Ghost of the Pines", "The frost-covered post is a throne for whoever waits longest."),
    "polarBearMother": ("Tender Ice", "A mother's love, rendered in whatever color you picked. She'd still eat you."),
    "penguins": ("Formal Occasion", "Congratulations. You've colored creatures that are already wearing tuxedos."),
    "ermineSnow": ("The White Thief", "Small, fast, and deadly. You spent ten minutes making it cute."),
    "icicleCave": ("Cathedral of Cold", "You colored ice. It would have melted either way."),
    "iceSkaters": ("Blades on Glass", "They glide effortlessly. You clicked on a screen. Roughly equivalent."),
    "snowCabin": ("Smoke and Stillness", "There's a warm cabin in this picture. You are not inside it."),
    "dogSledTeam": ("Eight Reasons to Run", "The dogs are working. You are not."),
    "arcticFox": ("Blue Hour Hunter", "The fox has survived blizzards, predators, and starvation. Your coloring helps none of that."),
    "iceFishingShanty": ("Patience Below Zero", "A small hut on a frozen lake. Inside: a person with more patience than you."),
    "mooseAtTwilight": ("Lord of the Gloaming", "The moose didn't ask to be colored. It doesn't know you exist. Mutual."),
    "owl": ("The Unblinking Judge", "The owl has been watching you this whole time. It has opinions."),
    "arcticFoxSnow": ("Vanishing Act", "White fox, white snow. You essentially colored nothing. Masterfully done."),
    "chineseNewYearDragon": ("Fury and Fortune", "The dragon brings luck. Whether that applies to you specifically remains to be seen."),
    "staveChurch": ("Timbers in the Snow", "A thousand-year-old church, faithfully colored in your lunch break."),
    "chickadeeWinterberry": ("Scarlet and Song", "The tiniest bird, the reddest berry, and now your fingerprints all over it."),
    "polarExpressTrain": ("Steam Through the Dark", "All aboard the train to exactly where you started, but slightly more relaxed."),
    "cozyCabin": ("Lamp in the Wilderness", "Somewhere, a real cabin like this exists. You could have booked it. Instead: this."),
    "foggyDock": ("Summit Solitude", "You just colored a mountain climber at the top of the world. They trained for years. You swiped."),
    "barnOwlHunting": ("The Silent Drop", "The barn owl kills with mathematical precision. Your coloring was more freeform."),
    "fishUnderIce": ("Suspended in the Cold", "The fish are frozen in place. Relatable."),
    "snowLeopard": ("Ghost of the Crags", "The snow leopard is so rarely seen that scientists doubt your coloring counts as an encounter."),
    "owlCornfieldMoon": ("The Fox's Long Nap", "That's a fox asleep under a rose arbor. Deeply unbothered. You could learn something."),
    "rooftopCellist": ("Jack-o'-Lanterns at Golden Hour", "Halloween porch at sunset. Spooky, warm, and utterly unrelated to a cellist."),
    "snowyOwlField": ("Open Sky Sentinel", "It sees everything across that field. Especially you, procrastinating."),
    "walrus": ("Throne of Blubber", "Two tons of confidence. Zero apologies. Honestly inspiring."),
    "lighthouseCliffs": ("Keeper of the Edge", "The lighthouse warns ships away from the rocks. No one built one to warn you away from this app."),
    "snowFox": ("The Powder Ghost", "The fox moves through snow like a secret. You filled it in with color. Secret's out."),
    "arcticOceanIce": ("The Midnight Crab", "That's a crab on a moonlit beach, not arctic ice. Excellent crustacean, though."),
    "foggyCoastMorning": ("The Rock Sovereign", "A sea lion on a wave-battered rock, utterly unbothered. Living the dream, technically."),
    "deepSeaAbyss": ("Drifting in Blue", "A jellyfish has no brain, no heart, and no plans. Today, you have something in common."),
    "barnOwl": ("The White Specter", "Barn owls scream instead of hoot. This image is calmer than that implies."),
    "barnAtDawn": ("First Light on the Loft", "The barn has been standing since before your great-grandparents. Your coloring took four minutes."),
    "rowboatLilyPond": ("The Watcher on the Fence", "That's an owl on a fence post in a cornfield. The rowboat is nowhere. The owl is judging."),
    "mountainHotSpring": ("Steam in the Peaks", "You colored warm water surrounded by mountains. The water didn't need your help."),
    "swanLakeValentine": ("Love, in Feathers", "Two swans forming a heart. Romantic. Also, swans are aggressive and territorial. Still romantic."),
    "mapleSyrupTapping": ("The Slow Harvest", "Patience rewarded with sweetness. This metaphor is doing a lot of heavy lifting for a coloring app."),
    "penguinColony": ("A Thousand Tuxedos", "You colored an entire colony. None of them will thank you. They have fish to think about."),
    "hibernatingHedgehog": ("Dreaming in Leaves", "The hedgehog is asleep and unavailable. Some days that's the goal."),
    "owlFamily": ("The Night Professors", "A family of owls staring in different directions. Efficient surveillance. Poor dinner conversation."),
    "deerBirchGrove": ("Between the White Trees", "The deer paused in the birch grove just long enough for you to color it. Now it's gone."),
    "winterGreenhouse": ("Warmth Against the Frost", "Glass and green things holding out against the cold. You colored it from inside a heated room."),
    "crossCountrySkier": ("The Long White Trail", "Miles of silence, effort, and snow. You captured all of that in about ninety seconds."),
    "coveredBridge": ("Where the Road Goes Dark", "The bridge has stood through floods, seasons, and now your creative vision. Impressive on both counts."),
    "lunarLanterns": ("Wishes Aloft", "Lanterns carrying hopes into the dark sky. Yours apparently included finishing a coloring."),
    "mardiGrasMasks": ("Faces for the Forgetting", "Behind every mask is a person making worse decisions than usual. Tradition is beautiful."),
    "hotSpring": ("The Thermal Pool", "Mineral-rich, geothermally heated water in a wild landscape. Your coloring: also warm, in spirit."),
    "robinSnowdrops": ("The First Announcement", "The robin is here to tell you spring is coming. You colored it. Message received."),
    "stoneWatermill": ("The Wheel Keeps Turning", "The mill has been grinding grain for centuries. You've been grinding this coloring for six minutes. Similar energy."),
    "polarBearCub": ("Small and Fearless", "It will grow to be enormous and dangerous. Right now it's just a problem for Future You."),
    "gondolaSkiLift": ("Up and Then Down", "The gondola takes you up the mountain so you can come back down. Life, essentially."),
    "frozenWaterfallBlue": ("Time, Stopped", "Water frozen mid-fall. The river had plans. Winter cancelled them."),
    "bisonYellowstone": ("The Old Continent", "The bison was here before everything else. It'll probably be here after. Humbly, you colored it."),
    "underwaterShipwreck": ("What the Sea Keeps", "A ship with a destination it never reached. The ocean filed it under 'mine now.'"),
    "machuPicchuLlama": ("Golden Fields, Quiet House", "That's a sunflower field with a farmhouse, not a llama at Machu Picchu. Honestly a peaceful upgrade."),
    "mountainLakeReflection": ("The Mirror Basin", "The mountain looks the same right-side up and upside down. You colored both. Efficient."),
    "lighthouseWinterStorm": ("Against the Gale", "The lighthouse stands in the storm. You colored it from wherever you are, presumably indoors."),
    "winterGardenGate": ("A Door to the Dormant", "The garden is sleeping. The gate is waiting. You are coloring. Everyone has their role."),
    "frozenPondFrog": ("Patient Under Glass", "The frog is frozen and unbothered. A master of the long game."),
    "winterTownSnowman": ("The Watcher of the Square", "The snowman sees everything that happens in this town. It will melt with all the secrets."),
    "hareSpringThaw": ("The Leap Between Seasons", "The hare is already moving. Spring doesn't wait, and neither does it."),
    "geeseMigration": ("The Annual Complaint", "Geese migrate thousands of miles while honking angrily the entire way. Respect."),
    "robinNestBlossoms": ("The Careful Engineers", "Robins build nests with architectural precision. You colored theirs with slightly less."),
    "cozyCabinSmoke": ("A Curl of Smoke", "Someone inside that cabin made a good decision a while ago. You are only now catching up."),
    "rockyCoastline": ("Where Land Argues with Sea", "The coastline is the result of a very long disagreement. Neither side has won."),
    "cherryBlossom": ("The Week That Matters", "Cherry blossoms last about a week. You spent some of your week on this. Seems fair."),
    "frozenCascade": ("The Paused River", "Ice captured motion mid-flight. Nature's longest exposure photograph."),
    "penguinFam": ("The Huddle", "The family that huddles together in subzero temperatures stays together. Mostly out of necessity."),
    "ottersThawingRiver": ("Loose in the Current", "Otters hold hands while sleeping so they don't drift apart. You just colored them. Unclench."),
    "springLambsDawn": ("New and Unsteady", "The lambs are approximately three days old and already better at mornings than you."),
    "cranePink": ("Rose and Grace", "The crane stands on one leg with more composure than you've displayed all week."),
    "kingfisher": ("The Feathered Bolt", "The kingfisher dives at 25 mph and catches fish with surgical accuracy. Different skills."),
    "vikingLongship": ("The Horizon Seekers", "They crossed oceans in wooden boats with no GPS. You navigated to this app. Different journeys."),
    "japaneseGarden": ("Still Water, Still Mind", "The garden was designed to calm the mind. Is it working? Only you know."),
    "deerDrinking": ("The Quiet Moment", "The deer came to drink. You came to color. Both of you found what you needed."),
    "greenhouseSeedlings": ("The Patient Beginning", "Small green things waiting to become large green things. Time is the only ingredient you can't add."),
    "kiteFestival": ("Color Against the Blue", "Kites are proof that doing something pointless beautifully is worthwhile. This app agrees."),
    "wisteriaFlowers": ("The Purple Cascade", "Wisteria smells extraordinary. This image cannot convey that. You'll have to imagine it."),
    "cherryBlossomTemple": ("Petals at the Gate", "The temple has been there for centuries. The blossoms come back every year. You showed up today. Good enough."),
    "porcupine": ("The Hedgehog's Kingdom", "That's a hedgehog, not a porcupine. Smaller, rounder, and significantly less dangerous."),
    "iceCave": ("The Blue Cathedral", "Inside the glacier, everything is blue and ancient and silent. You brought color to the silence."),
    "wisteriaArbor": ("The Violet Tunnel", "Walking under wisteria in bloom is one of life's better experiences. Coloring it is a distant second."),
    "redwoodCathedral": ("The Old Ones", "These trees were alive before most of history happened. You colored them anyway."),
    "seaTurtleCoral": ("Ancient and Unhurried", "The sea turtle has been doing this for 100 million years. It is not impressed by your efficiency."),
    "stargazerTelescope": ("The Bear in the Snow", "That's a brown bear in a snowy landscape. The telescope is elsewhere. The bear is not."),
    "bicycleHoneysuckle": ("The Slow Road", "A bicycle on a lane of honeysuckle. The slowest way to go somewhere, and often the best."),
    "ravenFoggyValley": ("The Black Messenger", "Ravens can remember your face and hold grudges. Color carefully."),
    "wildflowerHillside": ("The Vineyard Watch", "A hawk on a fence post above vineyard rows. Keeping tabs on the grapes, apparently."),
    "mistyMountainPines": ("The Beached Trawler", "That's an old fishing boat stranded on shore, not a misty mountain. Grounded in more ways than one."),
    "foxGardenArbor": ("Rowboat at Twilight", "An abandoned rowboat on a still pond with dragonflies. No fox, no arbor, just quiet."),
    "estuaryGoldenHour": ("Where the River Meets Gold", "The estuary catches the last light of the day. You caught it too, just a little later."),

    # ── April through June ──
    "peacockBlue": ("Plumage Unfurled", "A peacock spent 40 million years evolving that tail. You colored it in ten minutes. Nature wins."),
    "rainforestWaterfall": ("Cascade Without End", "The waterfall was falling before you got here. It'll keep falling after. You were merely a witness with crayons."),
    "redPanda": ("The Russet Daydreamer", "Red pandas sleep up to 13 hours a day. You just spent your free time coloring one. Who's really winning?"),
    "wolfMoonlight": ("Howl at Nothing", "The wolf is howling at the moon. The moon does not care. Neither does the wolf, honestly."),
    "butteryflyGarden": ("Flutter and Forget", "A butterfly lives for two weeks. You just immortalized one. It would not have done the same for you."),
    "windmillTulips": ("Turning Against the Wind", "Windmills have been doing this since the 1300s. Your contribution: a colored picture. Equally impactful."),
    "beeGarden": ("The Patient Pollinators", "Bees make one-twelfth of a teaspoon of honey in their lifetime. You've done less today."),
    "hummingbird": ("Wings Beyond Counting", "A hummingbird beats its wings 80 times per second. You are sitting very still coloring a picture of one."),
    "hillsideVillage": ("Terraced and Forgotten", "Somewhere, someone actually lives there. They're not coloring. They're doing taxes."),
    "samuraiGarden": ("Stillness Before the Strike", "The garden is raked. The sand is perfect. You've added color to someone else's serenity. Bold move."),
    "libraryRoom": ("Every Spine a Secret", "All those books and you chose to color the room instead of read any of them. Relatable."),
    "veniceGondola": ("Le Vélo de Personne", "A bicycle locked outside a café. Its owner is on their fourth espresso."),
    "harborRowboats": ("Tied and Waiting", "The boats are going nowhere. You are going nowhere. This is a perfect match."),
    "venetianCanal": ("Reflections on Nothing", "Venice is sinking. You colored it anyway. Optimistic or oblivious — hard to say."),
    "storkNest": ("Rooftop Tenure", "That stork has a better housing situation than most people you know."),
    "stoneArchCove": ("The Patient Shore", "The arch was carved by ten thousand years of waves. You colored it in six minutes."),
    "dragonfliesMeadow": ("Iridescent and Unbothered", "Dragonflies have been flying since before dinosaurs. Your coloring is a more recent development."),
    "wisteriaBridge": ("Heavy with Purple", "The wisteria doesn't need your help looking good. It's been doing this without you for years."),
    "koiPond": ("Circles Beneath the Surface", "The koi swim in slow, meditative circles. You have more in common than you thought."),
    "maroonTemple": ("Ochre and Devotion", "Built for centuries of worship. Used today as a coloring subject. The gods have seen worse."),
    "firefliesGlowing": ("Light Without Reason", "Fireflies blink to find love. You blinked and colored them. Only one of you succeeded tonight."),
    "harborLowTide": ("The Reluctant Shore", "Low tide reveals everything. The boats. The mud. The fact that you've been here coloring for a while."),
    "bambooForestPath": ("Path to Somewhere Quieter", "The bamboo grew three feet while you were coloring this. It's already ahead of you."),
    "parisianCafe": ("Rain, Bench, Nowhere to Be", "Someone is sitting alone in the rain under a street lamp. You've made it beautiful. They're still wet."),
    "gardenGateRoses": ("The Threshold of Bloom", "The gate is open. You could walk through. Instead you colored it. Some doors are best left as metaphors."),
    "windmill": ("Arms Against the Sky", "It grinds grain. It has a purpose. Not everything needs to be profound. Neither does this."),
    "wineCellar": ("Vintage Patience", "Every bottle in there is older than your most recent crisis. Perspective, courtesy of fermented grapes."),
    "wisteriaPergola": ("Draped in Violet Hours", "The wisteria approves of your coloring. Probably."),
    "jadeMountainMist": ("Rookery in the Fog", "Herons nest in cypress trees above still water, completely indifferent to your color choices."),
    "desertBloomSunset": ("Coyote at the Golden Edge", "The coyote stood at the edge of the desert at sunset and felt nothing. You colored it and felt something."),
    "rowboatShallows": ("Anchored in the Almost-Deep", "The rowboat isn't going anywhere. Neither are your Tuesday plans. Solidarity."),
    "riceTerraces": ("Staircase to the Sky", "These terraces were carved by hand over two thousand years. You colored them in one sitting."),
    "cappadociaBalloons": ("Drifting Without Itinerary", "The balloons go where the wind goes. You go where the app tells you. Freedom is relative."),
    "winterMarket": ("Lanterns in the Cold", "Hot mulled wine, chestnuts, people in large coats. You're at home on your phone. Different kinds of warmth."),
    "swanGliding": ("The Effort Beneath", "Above the surface: grace. Below: furious paddling. This is also a description of you, probably."),
    "hotAirBalloon": ("Still Water, Tall Sails", "A sailboat on a mirror-still lake, not a balloon. The mountains don't mind the confusion."),
    "driftwoodPebbles": ("What the Tide Left", "The sea considered these rocks and moved on. You considered them longer. Dedication or procrastination — hard to tell."),
    "dragonFly": ("Hover and Hold", "It can fly backwards, sideways, and upside down. You are sitting in a chair. Different skill sets."),
    "weirdBird": ("Inexplicably Confident", "This bird has no idea it's unusual. It has never had a single doubt. This is the energy."),
    "elephantFamily": ("The Long Memory", "Elephants remember everything. You already forgot why you opened this app."),
    "robinStoneWall": ("Perched and Unimpressed", "The robin has assessed the wall and found it adequate. It has assessed you similarly."),
    "wildflowerMeadow": ("Everything at Once", "Chaos with petals. The meadow has no plan and thrives anyway. Aspirational, honestly."),
    "prairieDogTown": ("Citizens of the Sightline", "Prairie dogs have sentinels, tunnels, and social hierarchies. You have a phone. They're probably doing better."),
    "magnoliaBlossoms": ("Before the Petals Fall", "Magnolias bloom for about a week. You've captured that forever, which is more than the tree managed."),
    "redBridge": ("Vermillion Crossing", "Someone built this bridge so people wouldn't get wet. You colored it. Both are valid contributions."),
    "tadpolePond": ("Everything Is Potential", "Every tadpole here is two weeks from having legs. You've been on your phone for longer."),
    "stainedGlassPeacock": ("Light Through Feathers", "The craftsperson spent months on this. You colored it in minutes. Efficiency or irreverence — the glass doesn't judge."),
    "sailboatLake": ("Sunday Velocity", "The sail is full. The lake is calm. Nobody appears to have anywhere urgent to be. Same."),
    "englishCottage": ("Roses at the Door", "Thatched roof, garden gate, roses in bloom. You've colored someone else's dream house. Practical? No. Cozy? Absolutely."),
    "openOceanSail": ("The Plunge", "A pelican just dove headfirst into the ocean from thirty feet up. You've done nothing that dramatic today."),
    "apiaryGoldenHour": ("The Hum of Industry", "Every bee here has a job and knows it. You are coloring a picture of their job. Work-life balance varies."),
    "kayakLakeshore": ("Paddle, Then Stillness", "The kayak is pulled up on shore. The lake is waiting. You are also waiting. For what, exactly?"),
    "kingfisherDive": ("Arrow Into Blue", "The kingfisher hits the water at 25 mph and catches fish every time. Your aim, in other areas, varies."),
    "wheelbarrowCatNap": ("Nap Without Apology", "The cat found a wheelbarrow and made it a bed. No context. No explanation. Aspirational behavior."),
    "forestFoxMushrooms": ("Between the Toadstools", "The fox paused in the mushroom forest. Then it became a coloring page. Life takes unexpected turns."),
    "hotAirBalloonLavender": ("Adrift in Purple Fields", "The balloon drifts over lavender and smells incredible from up there. You smell like wherever you're sitting."),
    "outdoorMovieNight": ("Credits Under Stars", "You're watching a screen to color a picture of people watching a screen. Layers."),
    "lighthouseWaves": ("Cranes by the Window", "Origami cranes wait by a window, folded from paper, expecting nothing. Quietly the most patient things in the room."),
    "thunderstormSunflowers": ("Before the Rain Hits", "The sunflowers know the storm is coming. You did not bring an umbrella."),
    "twilightHorizon": ("The Last Lit Edge", "The horizon doesn't linger. Neither does this moment. You colored it anyway. Good instinct."),
    "firefliesTwilight": ("Punctuation of Light", "Fireflies show up unrequested, unscheduled, unbothered. Blinking in the dark for the joy of it. Goals."),
    "hummingbirdGarden": ("Nectar and Velocity", "The hummingbird visited seventeen flowers while you colored this picture of one. It's doing fine."),
    "dragonBoatRace": ("Synchronized and Determined", "Forty people paddling in perfect unison. You can't agree with yourself about lunch. Respect the boat."),
    "floatingMarket": ("Commerce on the Water", "Mangoes, lemongrass, and someone steering with their feet. You managed to participate. Sort of."),
    "monetBridge": ("Impression of an Impression", "Monet painted this bridge obsessively for years. You colored a version today. Both valid, technically."),

    # ── July through September ──
    "castle": ("Ramparts at Dusk", "You colored a castle. Historically, castles were cold, drafty, and full of plague. Enjoy the nostalgia."),
    "mossyWaterfall": ("The Green Veil", "Nature made this in a million years. You colored it in twelve minutes. Roughly equivalent effort."),
    "hotAir": ("Adrift Above Everything", "You're coloring a balloon that goes wherever the wind takes it. Relatable, honestly."),
    "elephantSavanna": ("The Long Walk Home", "An elephant never forgets, and it will remember you colored it during work hours."),
    "heronMoonlitLake": ("Silver Water, Still Wings", "The heron has been standing there for hours. You've been sitting here for hours. More in common than you think."),
    "goldenSailboat": ("Light on the Water", "A boat going somewhere. You, however, are right here. Coloring."),
    "sunflowerFarmhouse": ("Late Summer, Warm Windows", "That's a hot air balloon over patchwork farmland. The sunflowers and farmhouse are elsewhere."),
    "treehouse": ("Up Among the Leaves", "A treehouse: the dream you had at age eight before you learned about property taxes."),
    "puffinCliff": ("Standing at the Edge", "The puffin looks ridiculous and thrives anyway. Take notes."),
    "ferrisWheelCarnival": ("Lights After Dark", "Round and round, going nowhere, endlessly lit up. The ferris wheel, and also this app."),
    "tuscanRoad": ("The Road to Somewhere Warm", "You've colored a road in Tuscany instead of actually going to Tuscany."),
    "wishingWellRoses": ("A Wish Left Unspoken", "You tossed time into a wishing well and got a colored image back. Seems fair."),
    "venice": ("The City on Still Water", "Venice is slowly sinking into the sea. Your coloring, at least, is timeless."),
    "vintageBiplane": ("Before Everything Got Complicated", "Leather helmets, open cockpits, and a 40% survival rate. Charming times."),
    "bicycleMorningGlories": ("Morning Without Agenda", "A bicycle going nowhere, wrapped in flowers. This image understands you."),
    "riverKayaking": ("Into the Current", "Someone is paddling hard through wild water. You are not. Yet here you are."),
    "fishingPierSunset": ("The Last Cast of the Day", "You colored a fishing pier. The fish are fine. They're always fine."),
    "trainStation": ("Departures", "Every train in this image is going somewhere. Inspirational, given your current activity level."),
    "fishVillage": ("Nets and Quiet Mornings", "A whole fishing village, faithfully rendered. The villagers will never know your sacrifice."),
    "townChurch": ("Sunday Light Through Stone", "Churches were built to inspire awe. You have inspired a single completed coloring. Close enough."),
    "tropicalSunsetCove": ("Heron in the Golden Marsh", "A great blue heron in golden marsh with dragonflies. Not a tropical cove, but arguably better."),
    "coralLagoon": ("Glass Water, Bright Sky", "A lagoon so still you could read your regrets in it. Or just color it."),
    "islandShoreline": ("The Borrowed Shell", "A hermit crab drags its home across the beach. You carry your phone everywhere. Not so different."),
    "ciderPressBarn": ("October in the Rafters", "Somewhere an actual cider press is making something delicious. You made this."),
    "redSquirrelPinecone": ("Small Ambitions, Sharp Teeth", "The squirrel has a plan for winter. Do you?"),
    "tropicalGardenBirds": ("The Green Watching", "A tree frog stares at you with the calm confidence of someone who has never paid rent."),
    "canoeLakeSunset": ("Stillness Before the Paddle Home", "A canoe at sunset. Serene. Nothing like whatever brought you here."),
    "tropicalFish": ("Snow on the Bridge", "A person with an umbrella walks a city bridge in the snow. The file says 'tropicalFish.' We regret nothing."),
    "shorebirdsFlats": ("Low Tide Reconnaissance", "Shorebirds scanning the flats with purpose. You scanning your phone. Somebody's being productive."),
    "heronGoldenHour": ("Patience in Gold Light", "The heron has stood motionless for three hours waiting for a fish. You've been here twelve minutes. Amateur."),
    "tidePools": ("Left Behind by the Sea", "Tide pools: nature's tiny aquariums, filled with creatures that sting you if you touch them."),
    "desertOasis": ("Mirage or Promise", "An oasis in the desert. You found it at the bottom of a coloring app."),
    "seahorse": ("The Slow Magnificent", "The seahorse moves at 5 feet per hour. Overachievers."),
    "tallLighthouse": ("The Fixed Point", "A lighthouse stands firm against everything the sea throws at it. Aspirational."),
    "volcanoIsland": ("Born from Beneath", "A volcano rising from the ocean. Your most intense Tuesday."),
    "lighthouseDusk": ("Warning Light at the Edge", "The lighthouse warns ships of danger. No one is warning you about how long you've been coloring."),
    "orcaBreaching": ("Thunder from the Deep", "An orca breaches the surface. Six tons of animal, pure joy, zero reasons."),
    "jungleWaterfall": ("Hidden in the Green", "Somewhere behind those leaves, a waterfall has been falling for centuries. Patient work."),
    "mermaidLagoon": ("The Myth at the Surface", "Mermaids: beautiful, fictional, suspiciously good at coloring apps. Or so the legend goes."),
    "tropicalWaterfall": ("Cascade into Warmth", "Water falls, the jungle hums. You are inside. With a phone. Balance is subjective."),
    "ospryDivingWaves": ("The Strike from Above", "An osprey dives at 80 mph with mathematical precision. You tapped a screen. Both valid."),
    "coralReef": ("Cardinal on the Ice", "A cardinal blazes red against a frozen branch. Whoever named this file has never seen a coral reef."),
    "octopusTidePool": ("Eight Arms, No Plans", "The octopus has three hearts, blue blood, and more intelligence than your to-do list."),
    "submarinePorthole": ("Pressure at Depth", "You're looking out a porthole into the deep ocean. Something is looking back. That's fine."),
    "pinkFlamingo": ("Absurd and Magnificent", "The flamingo is pink because of what it eats. You are what you consume. Consider your choices."),
    "hammockBeach": ("Between Two Palms", "A hammock between palms. No emails. You colored this from a device with 47 notifications pending."),
    "junglePool": ("Emerald and Shadow", "A jungle pool so still it reflects the canopy above. Your screen reflects your face. Less majestic."),
    "octopusGarden": ("In the Shade of the Sea", "The octopus built a garden out of shells. You built this. Roughly comparable achievements."),
    "sandDunes": ("The Shape of Wind", "Sand dunes: wind made visible, patience made landscape."),
    "strawberry": ("Red and Ready", "It's a strawberry. You colored it. It took longer than eating one would have."),
    "beachHammockBooks": ("No Schedule Until Monday", "A hammock, a beach, and books. The most aggressive display of peace you've ever colored."),
    "sunflowerDog": ("Joy, Unconditional", "A dog among sunflowers. Scientifically the most wholesome combination. You earned this one."),
    "sunflowerField": ("Ten Thousand Faces to the Sun", "A field of sunflowers, all facing the same direction. Leadership through phototropism."),
    "mangroveShallows": ("Slow Grace Underwater", "A manatee drifts through the shallows without urgency or apology. A role model."),
    "wetlandHerons": ("Kelp Forest Nap", "A sea otter floats in the kelp, holding its favorite rock. Lifestyle goals, honestly."),
    "tidalPoolStarfish": ("Poppies Without Reason", "A lone tree in a field of red poppies. No explanation. No apology. Just drama."),
    "stargazingCampfire": ("Small Fire, Infinite Sky", "You colored a campfire under stars. Somewhere, someone is actually doing this. Good for them."),
    "dolphinLeaping": ("Pure Speed, Pure Joy", "The dolphin leaped for no reason other than it could. Consider this energy."),
    "blueJelly": ("Drifting Without Direction", "A jellyfish has no brain, no heart, and no plan. It's been surviving for 500 million years."),
    "lanternFestival": ("A Sky Full of Wishes", "Lanterns rising into the dark. Every one a wish. Yours was apparently to color something."),
    "autumnTwilight": ("The Weasel at the Wall", "A stoat peers over a mossy stone wall with devastating confidence. It judges you gently."),
    "mantaRay": ("Shadow of the Deep", "A manta ray glides past, vast and silent. It did not notice you. It never will. That's okay."),
    "ospreyDive": ("Target Acquired", "The osprey locked on from sixty feet up. You have been staring at a screen for ten minutes. Different vibes."),
    "goldenCanyon": ("The Hedgehog Considers Autumn", "A hedgehog in a golden forest, surrounded by fallen leaves, unbothered. The content we deserved."),
    "humpbackWhale": ("The Song Beneath Everything", "A humpback's song travels thousands of miles. Your coloring, somewhat less far."),
    "sunsetBlaze": ("Barn Owl at the Orange Moon", "A barn owl banks over a golden field beneath a harvest moon. Haunting, gorgeous, and absolutely not a sunset blaze."),
    "slothRainforest": ("No Rush, No Regrets", "The sloth moves two miles per hour at peak effort. You've found your spirit animal."),
    "seaOtter": ("Floating, Just Floating", "A sea otter on its back, paws folded, entirely at peace. This is the life."),
    "fountain": ("The Center of the Square", "A fountain throws water into the air for no functional reason. Purely decorative. Deeply relatable."),
    "fishingTrawler": ("Out Before Dawn", "A fishing trawler at work before sunrise. You did not wake up before the sun today."),
    "mountainRowboat": ("Two Oars, One Direction", "A rowboat on a mountain lake. Quiet work, slow progress, beautiful surroundings. Metaphor optional."),
    "kelpForest": ("Cathedral of Green Light", "Sunlight through kelp: the original stained glass. No admission fee, but you do have to be underwater."),
    "pelicanColorful": ("The Absurd and Excellent", "The pelican holds three gallons of fish in its beak. It does not care what you think about it."),
    "moonlitHarbor": ("Reflections After Dark", "The harbor at night, perfectly still, perfectly lit. Nothing to do but look."),
    "stormPetrelSea": ("Dancing at the Edge", "A storm petrel skims waves in a gale. You can barely check email in a light drizzle."),
    "alpineMeadow": ("Above the Treeline", "A meadow where summer lasts eight weeks and nothing is complicated. You visited for eleven minutes."),
    "desertMesa": ("Ancient, Flat, and Patient", "A mesa that took a million years to erode. You colored it in fifteen minutes. Efficient."),
    "grizzlySalmon": ("The Brief Abundance", "A grizzly in the river, salmon in the air. Brief, brutal, beautiful."),
    "pingFlamingo": ("Standing Out in Pink", "Another flamingo. Still pink. Still absurd. Still magnificent. The flamingo accepts no notes."),
    "pirateShip": ("The Black Flag", "A pirate ship: freedom, danger, scurvy, and a complete lack of HR policies. Romantic in retrospect."),
    "jelly": ("Pulse and Drift", "A jellyfish pulsing through blue water, going wherever the current decides. Have you tried that?"),
    "crimsonSunrise": ("The Cabin in Amber Water", "An autumn lodge reflected in still water at twilight. Warm light, cold air, no deadlines. You're welcome."),
    "marshlandDawn": ("The First Light, Unhurried", "Dawn comes to the marsh whether anyone watches or not. Today, you watched. Briefly."),
    "emberGlow": ("Turkey in the Fallen Leaves", "A wild turkey picks through autumn leaves with great dignity and zero self-awareness. Inspirational."),
    "goldenForestLight": ("The Pheasant's Stroll", "A pheasant walks through golden wheat like it owns every acre. Technically, it does."),
    "autumnHarvestField": ("Ladder in the Last Light", "An apple orchard at sunset, ladder leaning. The harvest won't wait. You, however, are here."),
    "duskMarketSquare": ("The Badger at the Burrow", "A badger emerges into autumn leaves. Bold. Unhurried. Living its best life."),
    "harborMoonrise": ("Lightning Over Sunflowers", "A storm rolls in over a sunflower field, lightning cracking the sky. Ominous and gorgeous in equal measure."),
    "japanesePagoda": ("Tiers to Stillness", "A pagoda reaching upward, each level a little quieter than the last. Architecture as meditation."),
    "baldEagle": ("The Symbol, The Bird", "The bald eagle screams at everything and eats carrion without shame. America's complicated metaphor."),
    "countyFairSunset": ("Cotton Candy Light", "A county fair at golden hour. Funnel cake, improbable prizes, deeply questionable rides. You're nostalgic now."),
    "coastalTidePools": ("Stranded by the Tide", "Tiny worlds left behind by the sea. Each one complete. Each one temporary."),
    "harvestMoon": ("The Cellist and the City", "A cellist performs against a city skyline at sunset. The music carries further than the filename."),
    "coastalCliffs": ("The Long Drop to the Sea", "Cliffs that took centuries to carve. The sea is patient in a way you are not."),
    "eagleSouring": ("Thermal Climbing", "The eagle rides an invisible column of warm air upward, effortlessly. You rode a couch. Also valid."),
    "pandaBamboo": ("Lunch for Six Hours", "A panda eating bamboo: 40 pounds a day, 16 hours of eating. Finally, a lifestyle you understand."),
    "moroccanSouk": ("The Maze of Colors", "A souk where every alley leads somewhere interesting and nothing is priced clearly. Chaotic and wonderful."),
    "observatory": ("Pointed at the Dark", "An observatory aimed at light that left its source before humans existed. You pointed at a screen."),
    "parrot": ("Unsolicited Opinions", "The parrot will repeat everything you say. Either endearing or terrifying depending on what you've been saying."),
    "candyShop": ("Sugar and Consequence", "A candy shop: pure joy, immediate regret, eternal return."),
    "tidePoolStarfish": ("Five Arms, Zero Concern", "A starfish has no brain and regenerates its limbs. It is thriving."),
    "twoParrots": ("A Conversation Without End", "Two parrots talking. Neither is listening. Neither cares. Extremely relatable."),
    "cathedralInterior": ("Light Falling Through Stone", "A cathedral interior: centuries of careful light management, finally in your phone."),
    "clockworkGears": ("Everything Turning Together", "Gears inside gears, every motion connected. Like an app where coloring takes twenty minutes."),
    "romanAqueduct": ("Water Across the Ages", "Romans built this to move water across valleys. You can barely get WiFi to reach the kitchen."),
    "watchTower": ("Scanning the Horizon", "Someone built this to watch for trouble. From up here, they can see it coming."),
    "toucanPerched": ("The Impractical Beak", "The toucan's beak is a third of its body and serves as a heat radiator. Evolution was showing off."),
    "japaneseGardenKoi": ("Slow Circles in Still Water", "Koi move without urgency through still water. A complete philosophy in fish form."),
    "potteryWorkshop": ("Clay and Patience", "A pottery wheel asks for both hands. This app asked for a thumb. Lower bar."),
    "roadrunner": ("Gone Before You Look", "The roadrunner runs at 20 mph and prefers to outrun predators rather than fly. Efficiency as lifestyle."),
    "autumnStonehenge": ("The Old Stones in October", "Stonehenge in autumn: ancient, inexplicable, surrounded by tourists with phones. You fit right in."),
    "auroraLakeshore": ("Eagle Above the River Valley", "An eagle soars over a river valley. The northern lights are elsewhere, but the eagle compensates."),
    "canyonSunsetGlow": ("Cormorant at Harbor's End", "A cormorant dries its wings on a dock post against a harbor sunset. Dignified."),
    "blazingMapleCanopy": ("Desert Tortoise in Sunburst", "A tortoise in canyon rock, rays blazing behind it. Ancient, unhurried, unbothered by the filename."),
    "vineyardDusk": ("Egret in the Golden Water", "An egret wades through sunset-lit water, its reflection perfect. Elegant. Patient. Not a vineyard."),
    "ancientForestCanopy": ("Seedlings in the Greenhouse", "A warm potting shed full of young seedlings and quiet purpose. Growth happening slowly, deliberately."),
    "emeraldRainforest": ("Green Upon Green", "A rainforest so dense it swallows sound and light equally. You rendered it on a glass rectangle."),
    "summerMarshReeds": ("The Reeds and the Light", "A summer marsh at the hour when everything goes gold. You caught it. Briefly."),

    # ── October through December ──
    "purpleMoose": ("The Violet Wanderer", "A purple moose. Nature didn't do this. You did. Own it."),
    "moose": ("Lord of the Willows", "Somewhere a real moose is completely indifferent to your achievement."),
    "mushroomForest": ("Beneath the Fairy Ring", "You've colored a forest floor. The fungi thank you. Probably."),
    "ancientRuins": ("What Centuries Forget", "Civilizations rose and fell so you could color this. No pressure."),
    "autumnOrchard": ("The Heavy Boughs", "Apples don't pick themselves. Good thing you're here coloring them instead."),
    "greatWallAutumn": ("A Million Hands Built This", "You colored it in minutes. They built it in decades. Different vibes."),
    "mountainGoat": ("Effortless on the Edge", "The goat has never doubted itself. Take notes."),
    "cornfieldScarecrow": ("The Night Bibliophile", "A cat reads alone in a bookshop at midnight. Honestly, the dream."),
    "gazelleSavanna": ("Grace Under Pressure", "The gazelle is faster than you. At everything."),
    "autumnBarn": ("Red in the Amber Light", "A classic barn. Somewhere a farmer is doing actual work."),
    "redCoveredBridge": ("The Painted Crossing", "People crossed this bridge for centuries. You colored it in your pajamas."),
    "sleepyFox": ("Curled Against the Cold", "The fox is napping. You're coloring. Neither of you is being productive."),
    "birchTreesAutumn": ("The Gold Cathedral", "Birch trees didn't ask to be beautiful. They just are. Unlike most of us."),
    "bison": ("Weight of the Prairie", "The bison has survived everything. Your color choices are the least of its concerns."),
    "tigerStalking": ("Patient and Burning", "The tiger is hunting. You are coloring. The tiger is winning."),
    "coveredBridgeAutumn": ("October Crossing", "A covered bridge in fall. You've basically made a postcard nobody asked for."),
    "steamTrainViaduct": ("Iron Over the Valley", "Full steam ahead. Or just keep coloring at your own pace."),
    "bridgeAutumn": ("Reflection Season", "The bridge reflects on the water. You reflect on your life choices. Same energy."),
    "autumnBench": ("Waiting for No One", "An empty bench in autumn. Poetic. Slightly melancholy. Very you."),
    "woodworkShop": ("The Patient Craftsman", "Someone built real things here. You colored it. Still counts."),
    "autumnForestPath": ("Into the Amber Haze", "The path goes somewhere beautiful. You're not walking it. You're coloring it. Close enough."),
    "birdFish": ("Two Worlds, One Line", "Bird or fish? Yes. This is your life now."),
    "bioluminescentBay": ("The Sea Remembers Light", "Nature literally glows in the dark and you're just now paying attention."),
    "autumnParkBench": ("Still Afternoon", "Another bench. More autumn. You have a type."),
    "autumnEveningGlow": ("Dusk at the Henhouse", "A hen and her chicks at golden hour. Domestic. Warm. Unexpectedly wholesome."),
    "pumpkinPatchScarecrow": ("Guardian of the Gourds", "The scarecrow is doing its job. You are not doing yours."),
    "hauntedMansionDusk": ("The House Has Opinions", "It watches. It waits. It has seen your search history."),
    "dayOfTheDeadAltar": ("An Offering in Marigolds", "The dead are honored with flowers and candles. You honored them with crayons. Close enough."),
    "trickOrTreatNight": ("One Night the Rules Change", "Free candy, zero consequences. This holiday understood the assignment."),
    "foggyAutumnCemetery": ("The Quiet Tenants", "Peaceful, honestly. No meetings. No notifications. Just fog."),
    "cranberryGrove": ("The Great Wall at Harvest", "Mountains, color, and centuries of history. The dynasty is impressed."),
    "gorilla": ("The Weight of Thought", "The gorilla is contemplating something profound. Probably not this app."),
    "crystalCave": ("Geologic Patience", "These crystals took ten thousand years to form. You colored them in eight minutes."),
    "giantPanda": ("Unbothered, Munching", "The panda has no deadlines. No obligations. Just bamboo. The goal."),
    "rainyParis": ("The City Doesn't Stop", "Paris in the rain. Romantic if you're there. You're not."),
    "sushiBar": ("Precision and Ritual", "Someone trained for years to make this. You colored it between snacks."),
    "koala": ("Napping as Philosophy", "The koala sleeps twenty-two hours a day and has no regrets. Inspiring."),
    "streetLampReader": ("Moonlit Harvest", "A scarecrow under the full moon. It scares nothing. It knows things, though."),
    "cobblestoneAlley": ("Where the Maps End", "This alley goes nowhere in particular. Perfect."),
    "bakeryInterior": ("Proof and Patience", "Everything here took hours to make. Your coloring took minutes. The croissants judge you."),
    "terracedVineyard": ("Steps Toward the Vintage", "Vineyards are just agriculture. Beautiful, sloped, wine-producing agriculture. The best kind."),
    "alpacas": ("Fluffy and Unimpressed", "The alpacas have looked cuter with less effort than you've ever managed."),
    "bridgeAtDusk": ("The Last Light Holds", "Bridges at dusk are contractually obligated to be beautiful. This one complied."),
    "bookshopNight": ("The Fox Among Stories", "A fox on a snowy branch, surrounded by snowflakes. Living its best life. Are you?"),
    "oldCiderMill": ("Side A, Side B", "A vintage record player in a warm room. The needle drops. You have taste."),
    "cactusGarden": ("Thorns Are a Personality", "The cactus needs nothing from you. It was fine before you arrived."),
    "chameleo": ("Now You See It", "The chameleon is judging you from a color it just invented."),
    "tidalHarborBoats": ("The Tide Decides", "The boats go where the water says. You could learn something from that."),
    "cozyFarmhouseKitchen": ("Something Is Always Baking", "A farmhouse kitchen. Warm, cluttered, lived-in. The opposite of your browser tabs."),
    "autumnMoonrise": ("The Vine at Dusk", "Purple grapes at sunset, rows stretching to the horizon. You've basically colored wine."),
    "canyonCampfire": ("A Table Set for Ghosts", "Candles, wine glasses, white linen. Someone planned a dinner. No one has arrived."),
    "paperLanternRiver": ("Wishes on the Water", "Each lantern is someone's hope floating away. Yours is still loading."),
    "horseSleighWoodland": ("Through the Quiet Wood", "A horse-drawn sleigh on a snowy road. No engine noise. No podcast. Just hooves."),
    "reindeerBirchForest": ("Among the White Trees", "Reindeer in birch. Elegant by accident. Like most good things."),
    "thanksgivingTable": ("Set Before the Chaos", "The table is ready. The family is not. There is always one uncle."),
    "thanksgivingHarvestTable": ("An Abundance of Evidence", "You have colored more food than you will eat today. Probably."),
    "coveredBridgeSnow": ("By the Fireside", "A cabin interior with armchair and crackling fire. You're coloring it on a screen. Irony noted."),
    "heronDockDawn": ("Still Water, Still Hunter", "The heron has been standing there longer than your attention span."),
    "winterSolsticeBonfire": ("The Longest Night Burns", "The fire pushes back against the dark. You push back against your to-do list. Same instinct."),
    "dockFishingSunset": ("Line in the Water", "Nothing has been caught. Nothing needs to be. That's the whole point."),
    "holidayMarketNight": ("Sleigh Bells in the Pines", "A horse-drawn sleigh through snowy woods. Romantic. Cold. Decidedly pre-Uber."),
    "cardinalHolly": ("Red Against the White", "The cardinal didn't choose to be this beautiful. You chose to color it. Fair trade."),
    "ferrySunset": ("The Last Run of the Day", "The ferry crosses the same water twice a day and never tires of the view."),
    "christmasMarketNight": ("Glühwein and Good Intentions", "Twinkling lights, wooden stalls, strangers being briefly nice to each other. Cherish it."),
    "christmasFireplace": ("The Warmth We Manufacture", "A fire, a mantle, stockings hung. You've colored the idea of Christmas. That counts."),
    "gingerbreadHouseSnow": ("Structural Integrity Questionable", "It's made of candy. It will not survive spring. None of us will."),
    "frozenLakeFishing": ("Hole in the Ice", "You drilled a hole in a frozen lake to wait. Coloring this is the saner hobby."),
    "gingerbreadHouse": ("Sugar Architecture", "Edible real estate. Terrible investment. Wonderful afternoon."),
    "wreathWorkshop": ("Wound with Care", "Every loop intentional. Every bow debated. You respect the craft now."),
    "snowyVillageRooftops": ("Every Window a Story", "Each lit window hides a whole life. You colored the rooftops. That's enough."),
    "nutcrackerSoldier": ("Stiff but Loyal", "The nutcracker has one job, one expression, and no complaints. Aspirational."),
    "vintageToyTrain": ("A City in the Rain", "A coffee cup on a windowsill, city lights blurring in the wet glass. You've colored a mood."),
    "reindeerSleighNight": ("The Only Night That Matters", "Once a year, this makes perfect sense. You believe a little now."),
    "toyWorkshop": ("On Deadline, Always", "The elves have been at this longer than you've been alive. And they're cheerful about it. Suspicious."),
    "iceCastleAurora": ("Where the Sky Lives Inside", "Ice and light and impossible architecture. You're basically an architect now."),
    "snowmanTwilight": ("Brief and Perfect", "The snowman knows it's temporary. It smiles anyway. Unexpectedly wise."),
    "carolersSnowStreet": ("They Know All the Words", "Standing in the cold to sing for strangers. Bold. Unhinged. Festive."),
    "snowyPineTwilight": ("The Forest Holds Its Breath", "Snow on pines at dusk. The kind of quiet you keep forgetting exists."),
    "christmasTreeWindow": ("Framed in Evergreen", "Someone arranged this perfectly for a passing stranger. You're the stranger."),
    "snowGlobe": ("World in a Bubble", "Everything is fine inside the snow globe. Everything is always fine inside the snow globe."),
    "gingerbreadVillage": ("A Town Without Problems", "No traffic. No taxes. Just icing and good vibes."),
    "northernLightsCabin": ("Lit from Above", "The aurora doesn't perform on request. Tonight it did anyway."),
    "solsticeStones": ("Before the Clock", "Ancient stones aligned to the sun. Your calendar app cannot compete."),
    "santaWorkshop": ("The Operation Behind the Magic", "The logistics alone are staggering. You colored it instead of thinking about it. Smart."),
    "lighthouseIcyWaves": ("The Stubborn Light", "Waves, ice, darkness — and one light that refuses to quit. You get it."),
    "snowyChurchMidnight": ("Bells at the Edge of the Year", "Midnight. Snow. One lit window. The year is almost over. You colored tonight. Good enough."),
    "boxingDayRobin": ("The Morning After", "The robin showed up the day after Christmas, unbothered. Aspirational energy."),
    "frozenGrottoFalls": ("Ice Stopped Mid-Fall", "The waterfall froze in motion. Time paused for your coloring session. Respectful."),
    "deerWinterMoonlight": ("Silver Hour in the Clearing", "The deer stood still long enough to be painted. Mutual respect."),
    "cozyWindowNook": ("The World Outside", "Tea, a blanket, rain on the glass. You've colored the universal fantasy of opting out."),
    "stoneBridgeWinter": ("Unmoved by the Season", "Stone doesn't care about weather. You could learn something from stone."),
    "newYearsRooftop": ("The Countdown Belongs to Everyone", "Fireworks over the city. Another year, another round of optimism. Color it while it lasts."),
}

def escape_swift_string(s):
    """Escape a string for use in Swift source code."""
    return s.replace('\\', '\\\\').replace('"', '\\"')

def main():
    with open(SWIFT_PATH, 'r') as f:
        content = f.read()

    # Pattern to match each Artwork entry
    pattern = re.compile(
        r'(Artwork\(id:\s*"([^"]+)",\s*fileName:\s*"[^"]+",\s*displayName:\s*)"([^"]+)"'
        r'(,\s*completionMessage:\s*)"([^"]*(?:\\.[^"]*)*)"'
        r'(,\s*month:\s*\d+,\s*day:\s*\d+\))',
        re.DOTALL
    )

    found = set()
    missing = set()

    def replacer(m):
        artwork_id = m.group(2)
        if artwork_id in updates:
            found.add(artwork_id)
            new_display, new_msg = updates[artwork_id]
            return (
                m.group(1) + '"' + escape_swift_string(new_display) + '"' +
                m.group(4) + '"' + escape_swift_string(new_msg) + '"' +
                m.group(6)
            )
        else:
            missing.add(artwork_id)
            return m.group(0)

    new_content = pattern.sub(replacer, content)

    # Report
    total_catalog = len(found) + len(missing)
    print(f"Updated: {len(found)}/{total_catalog} entries")
    if missing:
        print(f"\nMissing from updates dict ({len(missing)}):")
        for m in sorted(missing):
            print(f"  - {m}")

    # Check for IDs in updates that weren't found in catalog
    not_in_catalog = set(updates.keys()) - found
    if not_in_catalog:
        print(f"\nIn updates but not in catalog ({len(not_in_catalog)}):")
        for n in sorted(not_in_catalog):
            print(f"  - {n}")

    with open(SWIFT_PATH, 'w') as f:
        f.write(new_content)

    print(f"\nWrote updated file to {SWIFT_PATH}")

if __name__ == "__main__":
    import os
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    main()
